# Generated by Django 4.0.4 on 2022-05-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lesson_4.place')),
            ],
        ),
    ]
