# Generated by Django 4.0.4 on 2022-05-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_field', models.IntegerField()),
                ('positive_field', models.PositiveIntegerField()),
                ('positive_small_field', models.PositiveSmallIntegerField()),
                ('big_integer_field', models.BigIntegerField()),
                ('float_field', models.FloatField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BinaryField()),
                ('char_field', models.CharField(max_length=5)),
                ('text_field', models.TextField(max_length=20)),
                ('date_field', models.DateField(auto_now=True)),
                ('date_time_field', models.DateTimeField(auto_now_add=True)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email_field', models.EmailField(max_length=254)),
                ('file_field', models.FileField(upload_to='file')),
                ('image_field', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_4.place'),
        ),
    ]
