# Generated by Django 4.0.4 on 2022-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0003_example_alter_hotel_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('teachers', models.ManyToManyField(to='lesson_4.teacher')),
            ],
        ),
    ]
