# Generated by Django 4.0.4 on 2022-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0005_categories_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
