# Generated by Django 4.0.4 on 2022-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0006_alter_product_photo_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(blank=True),
        ),
    ]
